---

- name: set certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/bin/certbot-auto
    mode: 0755

- name: get letsencrypt
  shell:  certbot-auto certonly --standalone -d {{ item.domain }} -m {{ item.email }} --agree-tos -n
  with_items:
    - "{{ certbot }}"
  when: "certbot is defined and ansible_distribution == 'CentOS'"

- name: get letsencrypt
  shell:  certbot-auto certonly --standalone -d {{ item.domain }} -m {{ item.email }} --agree-tos -n --debug
  with_items:
    - "{{ certbot }}"
  when: "certbot is defined and ansible_distribution == 'Amazon'"
