---

- name: set certbot
  git:
    repo: https://github.com/certbot/certbot
    dest: /usr/local/certbot
    version: master

- name: get letsencrypt
  shell:  /usr/local/certbot/certbot-auto certonly --standalone -d {{ item.domain }} -m {{ item.email }} --agree-tos -n
  with_items:
    - "{{ certbot }}"
  when: certbot is defined
